config/routes.rb
Eventually::Application.routes.draw do
  resources :events do
    collection do
      get :latest
    end
  end

end

app/models/event.rb
class Event
  include Mongoid::Document
  include Mongoid::Timestamps # adds created_at and updated_at fields

  field :series, type: String
  field :name, type: String
  field :speaker, type: String
  field :description, type: String
  field :venue, type: String
  field :date, type: Date, default: ->{ Date.today }
  field :start, type: Time, default: ->{ '19:00' }
  field :length, type: Integer, default: 180

  field :facebook_id, type: Integer
  field :srazy_url, type: String
  field :gplus_url, type: String

  default_scope desc(:created_at)

  before_validation :set_start_date, :fix_gplus_url

  # You can define indexes on documents using the index macro:
  # index :field <, :unique => true>

  # You can create a composite key in mongoid to replace the default id using the key macro:
  # key :field <, :another_field, :one_more ....>

  def self.latest
    self.first
  end

  def facebook_url
    "https://www.facebook.com/events/#{facebook_id}"
  end

  protected
  def set_start_date
    if date.is_a?(Date) && start.is_a?(Time)
      self.start = start.change(year: date.year, month: date.month, day: date.day)
    end
  end

  def fix_gplus_url
    return if gplus_url.blank?
    match = gplus_url.match(/\/events\/(\w+)/)
    if match
      self.gplus_url = "https://plus.google.com#{match[0]}"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  skip_before_filter :verify_authenticity_token, :only => [:latest]

  # GET /events
  def index
    @events = Event.all
  end

  # GET /events/1
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /events/1
  def update
    if @event.update_attributes(event_params)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
    redirect_to events_url, notice: 'Event was successfully destroyed.'
  end

  def latest
    @event = Event.latest
    respond_to do |format|
      format.html { render action: 'show' }
      format.js
    end
  end

  def bookmarklet
    @event = Event.latest
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:series, :name, :speaker, :description, :date, :start, :venue, :length, :facebook_id, :srazy_url, :gplus_url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarklet_helper.rb
module BookmarkletHelper
  def compile_invocation_script(url, options = {})
    default_error_message = "Something went wrong with the bookmarklet."
    error_message = options.has_key?(:error_message) ? options[:error_message] : default_error_message

    full_url = url
    if options.has_key?(:params)
      options[:params].each do |key,value|
        if !((full_url.ends_with? "?") || (full_url.ends_with? "&"))
          full_url += (full_url.include? "?") ? "&" : "?"
        end
        full_url += key + "=" + value
      end
    end

    return "javascript:(function(){var d=document,z=d.createElement('scr'+'ipt'),b=d.body;try{" +
      "if(!b)throw(0);z.setAttribute('src','" + full_url + "?r='+Math.random());b.appendChild(z);}" +
      "catch(e){alert('" + error_message + "');}}).call(this);"
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :series %><br />
    <%= f.text_field :series %>
  </div>
  <div class="field">
    <%= f.label :speaker %><br />
    <%= f.text_field :speaker %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :venue %><br />
    <%= f.text_field :venue %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_field :date, min: Date.today %>
  </div>
  <div class="field">
    <%= f.label :start %><br />
    <%= f.time_field :start %>
  </div>
  <div class="field">
    <%= f.label :length %><br />
    <%= f.number_field :length %>
  </div>

  <div class="field">
    <%= f.label :facebook_id %><br />
    <%= f.number_field :facebook_id %>
  </div>
  <div class="field">
    <%= f.label :srazy_url %><br />
    <%= f.text_field :srazy_url %>
  </div>
  <div class="field">
    <%= f.label :gplus_url %><br />
    <%= f.text_field :gplus_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<p>
  <a href="<%= compile_invocation_script(latest_events_url(format: :js)) %>">Bookmarklet</a>
</p>

<table>
  <thead>
    <tr>
      <th>Series</th>
      <th>Name</th>
      <th>Speaker</th>
      <th>Date</th>
      <th>Start</th>
      <th>Length</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
    <tr>
      <td><%= event.series %></td>
      <td><%= event.name %></td>
      <td><%= event.speaker %></td>
      <td><%= event.date %></td>
      <td><%= event.start.to_s(:time) %></td>
      <td><%= event.length %></td>
      <td><%= link_to 'Show', event %></td>
      <td><%= link_to 'Edit', edit_event_path(event) %></td>
      <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Event', new_event_path %>

app/views/events/index.txt.erb
<% @events.reverse.each do |event| %>
<div class="event">
<span class="date"><%= l(event.date, format: :long).downcase %></span>
<h3><%= event.name %></h3>
<div class="author"><%= event.speaker %></div>
<div class="links">
  <%= link_to 'Facebook', event.facebook_url %> |
  <%= link_to 'Google+', event.gplus_url %> |
  <%= link_to 'Srazy.info', event.srazy_url %>
</div>
<%= event.description %>
</div>

<% end %>

app/views/events/latest.js.erb
(function(document, window){
var data = <%= @event.to_json.html_safe %>;

var EventuallyBookmarklet = <%= Rails.application.class.assets.find_asset('bookmarklet.js').source.html_safe %>

EventuallyBookmarklet(data, document, window);

}(document,window));

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Series:</strong>
  <%= @event.series %>
</p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Venue:</strong>
  <%= @event.venue %>
</p>

<p>
  <strong>Speaker:</strong>
  <%= @event.speaker %>
</p>

<p>
  <strong>Description:</strong>
  <%= simple_format(@event.description) %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Start:</strong>
  <%= @event.start.to_s(:time) %>
</p>

<p>
  <strong>Length:</strong>
  <%= @event.length %>
</p>

<dl>
  <dt>Facebook</dt>
  <dd><%= link_to(@event.facebook_url, @event.facebook_url) %></dd>
  <dt>Srazy</dt>
  <dd><%= link_to(@event.srazy_url, @event.srazy_url) %></dd>
  <dt>Google+</dt>
  <dd><%= link_to(@event.gplus_url, @event.gplus_url) %></dd>
</dl>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Eventually</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>